
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: snowflake_customer_purchases
    description: "total purchase for each customer"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: cumulative_orders_by_date
    description: "total purchase for each customer"
    columns:
      - name: o_orderdate
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dates
  - name: incremental_time

  - name: playing_with_tests
    description: "playing_with_tests"
    columns:
      - name: c_custkey
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: c_mktsegment
        tests:
          - accepted_values:
              values: ['BUILDING','AUTOMOBILE','MACHINERY','HOUSEHOLD','FURNITURE']

          